# Generated by Django 5.0.6 on 2024-05-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
                ('password2', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=100)),
                ('lecturer_id', models.CharField(max_length=100)),
            ],
        ),
    ]
