# Generated by Django 5.0.6 on 2024-12-10 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='registration_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.number'),
        ),
        migrations.AlterField(
            model_name='number',
            name='number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
