# Generated by Django 5.0.6 on 2024-05-24 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_student_category_remove_student_lecturer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='lecturer_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='student_id',
        ),
    ]
