# Generated by Django 5.0.6 on 2024-12-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_profile_category_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
