# Generated by Django 5.0.6 on 2024-05-25 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_profile_lecturer_id_remove_profile_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
    ]
