# Generated by Django 5.0.6 on 2024-05-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_remove_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='firstname',
            field=models.CharField(default='John', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='lastname',
            field=models.CharField(default='Doe', max_length=50),
        ),
    ]
