# Generated by Django 5.0.6 on 2024-06-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='uploaded_at',
            field=models.DateTimeField(),
        ),
    ]
