# Generated by Django 5.0.6 on 2024-06-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_alter_note_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
